### PR TITLE
Ignore directories with missing Chart.yaml

### LINKED ISSUE #12: Ignore hidden folders when detecting charts or only package Charts with chart.yaml
If I have a charts repository, where the chart directories are in root instead of `charts/` or `stable/` etc, and I use
```yaml
      with:
        charts_dir: .
```
then the Pipeline failes with:
```
Installing chart-releaser...
Packaging chart '.github'...
Error: chart metadata (Chart.yaml) missing
```

Obviously .github dir contains the workflow files and not any charts.

Possible solutions:
* Ignore hidden folders by default, but make it configurable to exclude additional folders (e.g. `/docs`)
* Skip folders that do not have Chart.yaml in it. If there's an (invalid) chart without this file, then people will notice anyway that something is wrong, since the chart does not get published

### PR DESCRIPTION
**Pull request by ccremer**
Prevents action fails when there are directories detected that do not contain charts (e.g. `.github`)

as proposed in #12 

feedback welcome

fixes #12

### CODE REVIEW

**Comment by ccremer** [comment]
An example test run here: https://github.com/ccremer/charts/runs/531250478?check_suite_focus=true

File: cr.sh [hunk 1]
```diff
@@ -177,6 +177,17 @@ lookup_latest_tag() {
     fi
 }
 
+filter_changed_charts() {
```
Comment (unguiculus) [inline cr.sh:180]: The function generally filters charts and has no notion of changed charts. Please change the name.
```suggestion
filter_charts() {
```

File: cr.sh [hunk 2]
```diff
@@ -177,6 +177,17 @@ lookup_latest_tag() {
...
+    while read chart; do
+        local file="${chart}/Chart.yaml"
+        if [[ -f "${file}" ]]; then
+            echo ${chart}
+        else
+           echo "Warning: ${file} is missing, assuming that '${chart}' is not a helm chart. Skipping." 1>&2
```
Comment (unguiculus) [inline cr.sh:186]: Remove braces to match existing style.
```suggestion
        local file="$chart/Chart.yaml"
        if [[ -f "$file" ]]; then
            echo "$chart"
        else
           echo "Warning: $file is missing, assuming that '$chart' is not a Helm chart. Skipping." 1>&2
```

File: cr.sh [hunk 3]
```diff
@@ -190,7 +201,7 @@ lookup_changed_charts() {
         fields='1,2'
     fi
 
-    cut -d '/' -f "$fields" <<< "$changed_files" | uniq
+    cut -d '/' -f "$fields" <<< "$changed_files" | uniq | filter_changed_charts
```
Comment (unguiculus) [inline cr.sh:204]:
```suggestion
    cut -d '/' -f "$fields" <<< "$changed_files" | uniq | filter_charts
```

**Comment by ccremer** [comment]
Thanks for the review! I updated my commit.

File: cr.sh [hunk 4]
```diff
@@ -177,6 +177,17 @@ lookup_latest_tag() {
     fi
 }
 
+filter_charts() {
+    while read chart; do
+        local file="$chart/Chart.yaml"
+        if [[ -f "$file" ]]; then
+            echo $chart
+        else
+           echo "Warning: $file is missing, assuming that '$chart' is not a Helm chart. Skipping." 1>&2
```
Comment (unguiculus) [inline cr.sh:186]: Just one more thing to match the existing style.
```suggestion
           echo "WARNING: $file is missing, assuming that '$chart' is not a Helm chart. Skipping." >&2
```

File: cr.sh [hunk 5]
```diff
@@ -177,6 +177,17 @@ lookup_latest_tag() {
     fi
 }
 
+filter_charts() {
+    while read chart; do
+        local file="$chart/Chart.yaml"
```
Comment (scottrigby) [inline cr.sh:182]: Since we're filtering anyway we may as well filter out files silently, so we don't get messages like:
> README.md/Chart.yaml is missing, assuming that 'README.md' is not a helm chart

For example:

```suggestion
        [[ ! -d $chart ]] && continue
        local file="$chart/Chart.yaml"
```

**Comment by ccremer** [comment]
Added your suggestions.
Example output (commit contains a change in README.md, which is not logged now):
```console
Looking up latest tag...
Discovering changed charts since 'znapzend-0.3.1'...
WARNING: .github/Chart.yaml is missing, assuming that '.github' is not a Helm chart. Skipping.
Installing chart-releaser...
Packaging chart 'znapzend'...
Successfully packaged chart and saved it to: .cr-release-packages/znapzend-0.3.1.tgz
Releasing charts...
```

**Comment by scottrigby** [comment]
I added a [fixes](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) comment to the description above to automatically close related issue on PR merge

**Comment by SamuAlfageme** [comment]
Would be nice to have a `v1.0.0-rc.3` with whis one in. For repos with:

```yaml
        with:
          charts_dir: .
```

... this fails `Packaging chart '.github'` (the dir containing the action's workflow itself)
